spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: profile-service
              uri: ${PROFILE_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/profile/**

            - id: career-service
              uri: ${PROFILE_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/career/**

            - id: skills-service
              uri: ${PROFILE_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/skills/**

            - id: education-service
              uri: ${PROFILE_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/education/**

            - id: achievements-service
              uri: ${PROFILE_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/achievements/**

            - id: hobbies-service
              uri: ${PROFILE_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/hobbies/**

            - id: certifications-service
              uri: ${PROFILE_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/certifications/**

            - id: projects-service
              uri: ${PROFILE_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/projects/**


      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always